# Training
exp_name : xgb1-result
model_name : xgboost
model_save_dir : ../models/
result_dir : ../results/

# Inference
inference_model_path : ../models/xgb-result

# Data
train_data_path : ../data/train/KNOW_2017.csv
test_data_path : ../data/test/KNOW_2017_test.csv
preprocessing : False

# Hyper Parameters
hp :
  xgboost:
    n_estimators : 100
    use_label_encoder : False
    learning_rate : False 
    verbosity : False
    objective : "multi:softmax"
    booster : False
    tree_method : False
    n_jobs : -1
    reg_alpha : False
    reg_lambda : False
    random_state : 20210827

  lightgbm:


  torch: